### ISSUE TITLE
[BUG] Marche pas

### ISSUE THREAD

**Issue by ezshad** [yoannchb-pro/MoodleGPT#35]
Hello !

J'ai cette erreur dans la console quand je teste l'extension localement avec le faux quiz moodle : 

Failed to load resource: the server responded with a status of 404 ()
MoodleGPT.js:1 TypeError: Cannot read properties of undefined (reading '0')
    at MoodleGPT.js:1:8845
    at Generator.next (<anonymous>)
    at s (MoodleGPT.js:1:269)

J'ai vu que ca pouvait être du au fait que je n'avais pas de fonds sur mon compte OpenAI. J'ai pourtant mis 5$ dessus donc je ne comprends pas.. Peux-tu m'aider stp ? Merci !

**Comment by ezshad** [comment]
J'ai changé le model GPT et ca marche. Merci !
